- alias: evan
  official: True
  name: Evan Kiefl
  avatar: bio-photo.jpg
  twitter: evankiefl
  github: ekiefl
  email: kiefl.evan@gmail.com

- alias: kourtney
  official: True
  name: Kourtney Kroll
  avatar: kourtney-photo.png
  email: kkroll@uchicago.edu
