- alias: evan
  official: True
  name: Evan Kiefl
  twitter: evankiefl
  github: ekiefl
  email: kiefl.evan@gmail.com

- alias: kourtney
  official: True
  name: Kourtney Kroll
  email: kkroll@uchicago.edu
